<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        // Insertar módulos estáticos de Administrativos
        $administrativosModules = [
            [
                'name' => 'talento-humano',
                'display_name' => 'Talento Humano',
                'description' => 'Gestión de personal y recursos humanos',
                'route' => '/administrativos/talento-humano',
                'icon' => 'Users',
                'role' => 'Administrativos',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ciau',
                'display_name' => 'CIAU',
                'description' => 'Centro de Información y Atención al Usuario',
                'route' => '/administrativos/ciau',
                'icon' => 'Shield',
                'role' => 'Administrativos',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'sistemas-informacion',
                'display_name' => 'Sistemas de Información',
                'description' => 'Gestión de sistemas informáticos y tecnología',
                'route' => '/administrativos/sistemas-informacion',
                'icon' => 'Settings',
                'role' => 'Administrativos',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'gestion-tecnica-logistica',
                'display_name' => 'Gestión Técnica Logística',
                'description' => 'Gestión de recursos técnicos y logísticos',
                'route' => '/administrativos/gestion-tecnica-logistica',
                'icon' => 'Settings',
                'role' => 'Administrativos',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'farmacia',
                'display_name' => 'Farmacia',
                'description' => 'Gestión farmacéutica y medicamentos',
                'route' => '/administrativos/farmacia',
                'icon' => 'Heart',
                'role' => 'Administrativos',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar módulos estáticos de Asistenciales
        $asistencialesModules = [
            [
                'name' => 'ambulatorio',
                'display_name' => 'Ambulatorio',
                'description' => 'Gestión de consulta externa y ambulatoria',
                'route' => '/asistenciales/ambulatorio',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'hospitalizacion',
                'display_name' => 'Hospitalización',
                'description' => 'Gestión de hospitalización y cuidados',
                'route' => '/asistenciales/hospitalizacion',
                'icon' => 'Heart',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'urgencias',
                'display_name' => 'Urgencias',
                'description' => 'Gestión de servicios de urgencias',
                'route' => '/asistenciales/urgencias',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'laboratorio',
                'display_name' => 'Laboratorio',
                'description' => 'Gestión de laboratorio clínico',
                'route' => '/asistenciales/laboratorio',
                'icon' => 'BarChart3',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'imagenes',
                'display_name' => 'Imágenes',
                'description' => 'Gestión de imágenes diagnósticas',
                'route' => '/asistenciales/imagenes',
                'icon' => 'BarChart3',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'cirugia',
                'display_name' => 'Cirugía',
                'description' => 'Gestión de servicios quirúrgicos',
                'route' => '/asistenciales/cirugia',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'ginecologia',
                'display_name' => 'Ginecología',
                'description' => 'Gestión de servicios ginecológicos',
                'route' => '/asistenciales/ginecologia',
                'icon' => 'Heart',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'medicina-fisica',
                'display_name' => 'Medicina Física',
                'description' => 'Gestión de medicina física y rehabilitación',
                'route' => '/asistenciales/medicina-fisica',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mortalidad',
                'display_name' => 'Mortalidad',
                'description' => 'Gestión y análisis de mortalidad',
                'route' => '/asistenciales/mortalidad',
                'icon' => 'BarChart3',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'epidemiologia',
                'display_name' => 'Epidemiología',
                'description' => 'Gestión epidemiológica y vigilancia',
                'route' => '/asistenciales/epidemiologia',
                'icon' => 'BarChart3',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'banco-sangre',
                'display_name' => 'Banco de Sangre',
                'description' => 'Gestión del banco de sangre y hemoderivados',
                'route' => '/asistenciales/banco-sangre',
                'icon' => 'Heart',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'extension-hospitalaria',
                'display_name' => 'Extensión Hospitalaria',
                'description' => 'Gestión de extensión hospitalaria',
                'route' => '/asistenciales/extension-hospitalaria',
                'icon' => 'Heart',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'uci-adultos',
                'display_name' => 'UCI Adultos',
                'description' => 'Gestión de Unidad de Cuidados Intensivos Adultos',
                'route' => '/asistenciales/uci-adultos',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'uci-pediatrico',
                'display_name' => 'UCI Pediátrico',
                'description' => 'Gestión de Unidad de Cuidados Intensivos Pediátricos',
                'route' => '/asistenciales/uci-pediatrico',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'uci-neonatal',
                'display_name' => 'UCI Neonatal',
                'description' => 'Gestión de Unidad de Cuidados Intensivos Neonatal',
                'route' => '/asistenciales/uci-neonatal',
                'icon' => 'Activity',
                'role' => 'Asistenciales',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar módulos estáticos de Financieros
        $financierosModules = [
            [
                'name' => 'facturacion',
                'display_name' => 'Facturación',
                'description' => 'Gestión de facturación y cobros',
                'route' => '/financieros/facturacion',
                'icon' => 'FileText',
                'role' => 'Financieros',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'cartera',
                'display_name' => 'Cartera',
                'description' => 'Gestión de cartera y cuentas por cobrar',
                'route' => '/financieros/cartera',
                'icon' => 'BarChart3',
                'role' => 'Financieros',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'recaudo',
                'display_name' => 'Recaudo',
                'description' => 'Gestión de recaudos y pagos',
                'route' => '/financieros/recaudo',
                'icon' => 'BarChart3',
                'role' => 'Financieros',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'glosas',
                'display_name' => 'Glosas',
                'description' => 'Gestión de glosas médicas',
                'route' => '/financieros/glosas',
                'icon' => 'FileText',
                'role' => 'Financieros',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'presupuesto',
                'display_name' => 'Presupuesto',
                'description' => 'Gestión presupuestal y planificación financiera',
                'route' => '/financieros/presupuesto',
                'icon' => 'BarChart3',
                'role' => 'Financieros',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'contabilidad',
                'display_name' => 'Contabilidad',
                'description' => 'Gestión contable y estados financieros',
                'route' => '/financieros/contabilidad',
                'icon' => 'FileText',
                'role' => 'Financieros',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar módulos estáticos de Calidad
        $calidadModules = [
            [
                'name' => 'pamec',
                'display_name' => 'PAMEC',
                'description' => 'Programa de Auditoría para el Mejoramiento de la Calidad',
                'route' => '/calidad/pamec',
                'icon' => 'Shield',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'documentos',
                'display_name' => 'Documentos',
                'description' => 'Gestión documental de calidad',
                'route' => '/calidad/documentos',
                'icon' => 'FileText',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'habilitacion',
                'display_name' => 'Habilitación',
                'description' => 'Gestión de habilitación y cumplimiento normativo',
                'route' => '/calidad/habilitacion',
                'icon' => 'Shield',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'indicadores',
                'display_name' => 'Indicadores',
                'description' => 'Gestión de indicadores de calidad',
                'route' => '/calidad/indicadores',
                'icon' => 'BarChart3',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'auditoria',
                'display_name' => 'Auditoría',
                'description' => 'Gestión de auditorías de calidad',
                'route' => '/calidad/auditoria',
                'icon' => 'Shield',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'mejoramiento',
                'display_name' => 'Mejoramiento',
                'description' => 'Gestión de mejoramiento continuo',
                'route' => '/calidad/mejoramiento',
                'icon' => 'Activity',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'humanizacion',
                'display_name' => 'Humanización',
                'description' => 'Gestión de humanización en la atención',
                'route' => '/calidad/humanizacion',
                'icon' => 'Heart',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'referenciaciones',
                'display_name' => 'Referenciaciones',
                'description' => 'Gestión de referencias y contrarreferencias',
                'route' => '/calidad/referenciaciones',
                'icon' => 'Activity',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'tecnovigilancia',
                'display_name' => 'Tecnovigilancia',
                'description' => 'Gestión de tecnovigilancia y dispositivos médicos',
                'route' => '/calidad/tecnovigilancia',
                'icon' => 'Settings',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'centro-escucha',
                'display_name' => 'Centro de Escucha',
                'description' => 'Atención y seguimiento a usuarios',
                'route' => '/calidad/centro-escucha',
                'icon' => 'Activity',
                'role' => 'Calidad',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar módulos estáticos de Direccionamiento
        $direccionamientoModules = [
            [
                'name' => 'plan-desarrollo',
                'display_name' => 'Plan de Desarrollo',
                'description' => 'Gestión y seguimiento del plan de desarrollo institucional',
                'route' => '/direccionamiento/plan-desarrollo',
                'icon' => 'Target',
                'role' => 'Direccionamiento',
                'active' => true,
                'content_type' => 'module',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Insertar todos los módulos
        DB::table('modules')->insert(array_merge(
            $administrativosModules,
            $asistencialesModules,
            $financierosModules,
            $calidadModules,
            $direccionamientoModules
        ));
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        // Eliminar módulos estáticos insertados
        $moduleNames = [
            // Administrativos
            'talento-humano', 'ciau', 'sistemas-informacion', 'gestion-tecnica-logistica', 'farmacia',
            // Asistenciales
            'ambulatorio', 'hospitalizacion', 'urgencias', 'laboratorio', 'imagenes', 'cirugia',
            'ginecologia', 'medicina-fisica', 'mortalidad', 'epidemiologia', 'banco-sangre',
            'extension-hospitalaria', 'uci-adultos', 'uci-pediatrico', 'uci-neonatal',
            // Financieros
            'facturacion', 'cartera', 'recaudo', 'glosas', 'presupuesto', 'contabilidad',
            // Calidad
            'pamec', 'documentos', 'habilitacion', 'indicadores', 'auditoria', 'mejoramiento',
            'humanizacion', 'referenciaciones', 'tecnovigilancia', 'centro-escucha',
            // Direccionamiento
            'plan-desarrollo'
        ];

        DB::table('modules')->whereIn('name', $moduleNames)->delete();
    }
};
